config/routes.rb
StuffManagement::Application.routes.draw do
  resources :tests

  resources :comments

  resources :forums

  get "search/byid"

  get "search/byname"

  get "search/byidresult"

  get "search/bynameresult"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  resources :users
  resources :users do 
    get :updateidentity, on: :member
  end

  get "welcome/index"

  resources :departments

  resources :employees

  root to: 'welcome#index', as: 'welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation, :identity
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    if User.find(session[:user_id]).identity != "administrator"
      redirect_to admin_url
    else
      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @users }
      end

    end

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.identity = "normal"

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_url, notice: "User #{@user.name} was successfully created."}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if User.find(session[:user_id]).identity != "administrator"
      redirect_to admin_url
    else
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
    end
  end


  def updateidentity
    if User.find(session[:user_id]).identity == "administrator"
      @user = User.find(params[:id])
      @user.identity = "administrator"
      @user.save
      redirect_to users_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>输入账号信息</legend>

    <div>
      <%= f.label :账号 %>:
      <%= f.text_field :name, size: 40 %>
    </div>

    <div>
      <%= f.label :password, '密码' %>:
      <%= f.password_field :password, size: 40 %>
    </div>

    <div>
      <%= f.label :password_confirmation, '确认密码' %>:
      <%= f.password_field :password_confirmation, size: 40 %>
    </div>

    <div>
      <%= f.submit %>
    </div>

  </fieldset>



<% end %>
</div>

app/views/users/edit.html.erb
<h1>账号密码修改</h1>


<div class="depot_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>输入账号信息</legend>

    <div>
      <%= f.label :账号 %>:
      <%= @user.name %>
    </div>

    <div>
      <%= f.label :password, '密码' %>:
      <%= f.password_field :password, size: 40 %>
    </div>

    <div>
      <%= f.label :password_confirmation, '确认密码' %>:
      <%= f.password_field :password_confirmation, size: 40 %>
    </div>

    <div>
      <%= f.submit %>
    </div>

  </fieldset>



<% end %>
</div>

app/views/users/index.html.erb
<h1>所有用户</h1>

  <% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>


<table>
  <tr>
    <th>账号</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to '显示', user %></td>
    <td><%= link_to '编辑', edit_user_path(user) %></td>
    <% if user.identity != "administrator" %>
     <td><%= link_to '删除', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% if User.find(session[:user_id]).identity == "administrator" %>
        <td>
          <%= link_to '提升为管理员', updateidentity_user_path(user) %>
        </td>
      <% end %>
    <% end %>

  </tr>
<% end %>
</table>

<br />

<%= link_to '新建用户', new_user_path %>

app/views/users/new.html.erb
<h1>注册用户</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>账号:</b>
  <%= @user.name %>
</p>

<p>
  <b>编码后的密码:</b>
  <%= @user.password_digest %>
</p>


<%= link_to '修改', edit_user_path(@user) %> |
<%= link_to '返回', users_path %>