config/routes.rb
StuffManagement::Application.routes.draw do
  resources :tests

  resources :comments

  resources :forums

  get "search/byid"

  get "search/byname"

  get "search/byidresult"

  get "search/bynameresult"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  resources :users
  resources :users do 
    get :updateidentity, on: :member
  end

  get "welcome/index"

  resources :departments

  resources :employees

  root to: 'welcome#index', as: 'welcome'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :ctime, :forum_id, :message, :name
  validates :message, presence: true
  belongs_to :forum 
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name, :remark
  has_many :employees
  before_destroy :ensure_not_referenced_by_any_employee

  private
  	def ensure_not_referenced_by_any_employee
  		if employees.empty?
  			return true
  		else
  			errors.add(:base, 'Employee present')
  			return false
  		end
  	end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :age, :nbirth, :bumen, :eid, :nintodepartmentdate, :marriage, :name, :nation, :pay, :remark, :sex, :nworkdate
  validates :age, :nbirth, :bumen, :eid, :nintodepartmentdate, :marriage, :name, :nation, :pay, :remark, :sex, :nworkdate, presence: true
  validates :eid, uniqueness: true
  validates :age, numericality: {greater_than_or_equal_to: 1}
  belongs_to :department
  attr_accessible :department_id
  attr_accessible :department

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :number, :createtime, :fcontent, :postuser, :title, :last_postdate
  validates :title, :fcontent, presence: true
  has_many :comments, dependent: :destroy
end

app/models/test.rb
class Test < ActiveRecord::Base
  attr_accessible :time
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation, :identity
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_employees = Employee.count
  	@total_departments = Department.count
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tests }
    end
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
    @test = Test.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test }
    end
  end

  # GET /tests/new
  # GET /tests/new.json
  def new
    @test = Test.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test }
    end
  end

  # GET /tests/1/edit
  def edit
    @test = Test.find(params[:id])
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(params[:test])

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render json: @test, status: :created, location: @test }
      else
        format.html { render action: "new" }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tests/1
  # PUT /tests/1.json
  def update
    @test = Test.find(params[:id])

    respond_to do |format|
      if @test.update_attributes(params[:test])
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test = Test.find(params[:id])
    @test.destroy

    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    if User.find(session[:user_id]).identity != "administrator"
      redirect_to admin_url
    else
      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @users }
      end

    end

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.identity = "normal"

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_url, notice: "User #{@user.name} was successfully created."}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if User.find(session[:user_id]).identity != "administrator"
      redirect_to admin_url
    else
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
    end
  end


  def updateidentity
    if User.find(session[:user_id]).identity == "administrator"
      @user = User.find(params[:id])
      @user.identity = "administrator"
      @user.save
      redirect_to users_url
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

<% if session[:user_id] and session[:user_name]%>

	您好！<%= session[:user_name] %>
<% end %>
<br>

现在的时间是 <%= Time.now %> 
<br>
	公司当前所拥有的员工数为 <%= @total_employees %>
	<br>员工工资总和为
	<% a = 0 %>
	<% Employee.all.each do |employee| %>
	<% a = a + employee.pay %>
	<% end %>
	<%= a %>

<br><br>
	公司当前所拥有的部门数量为 <%= @total_departments %>
	<% Department.all.each do |department| %>
	<br>	<% a = 0 %>
		<% b = 0 %>
		<% Employee.all.each do |employee| %>
			<% if employee.bumen == department.name %>
				<% a = a + 1 %>
				<% b = b + employee.pay %>
			<% end %>
		<% end %>

		<%= department.name %>拥有<%= a %>个员工，总工资为<%= b %>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>企业职工人事管理信息系统</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

	<div id="banner">
		<%= image_tag("logo.png") %> 
		<%= @page_title || "企业职工人事管理信息系统" %> 
	</div>

	<div id="columns">
		<div id="side">
			<ul>
				
				<% if session[:user_id] and session[:user_name] %>
					<% if User.find(session[:user_id]).identity == "normal" %>
						<li>您好！尊敬的普通用户<%= session[:user_name] %></li>
					<% else %>
						<li>您好！尊敬的管理员<%= session[:user_name] %></li>
						<li><%= button_to '用户列表', users_path, method: :get %></li>
					<% end %>

					<%= button_to '修改密码', edit_user_path(id: session[:user_id]), method: :get%>
					<%= button_to '登出', logout_path, method: :delete%>
					<li><%= button_to '统计信息', admin_path, method: :get %></li>
				<li><%= button_to '员工信息', employees_path, method: :get %></li>
				<li><%= button_to '部门信息', departments_path, method: :get %></li>
				<li><%= button_to '公司讨论群', forums_path, method: :get %></li>
				<% else %>
					<li> 您当前处于游客状态，将不能进行任何操作，请注册登陆</li>
					<li><%= button_to '注册', new_user_path, method: :get %>

						<%= button_to '登陆', login_path, method: :get %>
					</li>
				<% end %>
			</ul>
		</div>

		<div id="main">
			<%= yield %>
		</div>
	</div>

</body>
</html>